### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'indexOf')   

### ISSUE THREAD

**Issue by Jiuyun-Wang** [onfido/onfido-sdk-ui#1777]
### What was the expected behaviour?

Should be able import init.

### What happened instead?

TypeError: Cannot read properties of null (reading 'indexOf')   

### Version info:
v6.19.0

- Onfido SDK: 6.19.0
- OS: Mac
- Browse: Chrom
- Device: Macbook
- Node: v17.2.0
- Framework or relevant dependencies (if applicable)

### Integration configuration:

import { init } from "onfido-sdk-ui";

        onfidoSdk = init({
            token: onfidoToken,
            containerId: 'onfido-mount',
            containerEl: <div id="root" />, //ALTERNATIVE to `containerId`
            onComplete: function (data) {
              console.log('everything is complete')
            },
            steps: ['welcome', 'document', 'face', 'complete'],
          })

### Steps to reproduce:

  ● Test suite failed to run

    TypeError: Cannot read properties of null (reading 'indexOf')

      4 |
      5 | import { onfidoApi } from "../../api";
    > 6 | import { init } from "onfido-sdk-ui";
        | ^
      7 | //import { init } from 'onfido-sdk-ui/dist/onfidoAuth.min.js';
      8 | //const Onfido = require("onfido-sdk-ui")
      9 |

      at Object.<anonymous> (node_modules/supports-webp/dist/supports-webp.common-js.js:6:62)
      at Object.resolve (node_modules/onfido-sdk-ui/lib/webpack:/external "supports-webp":1:18)
      at t (node_modules/onfido-sdk-ui/lib/webpack:/webpack/bootstrap:38:19)
      at Module.resolve (node_modules/onfido-sdk-ui/lib/index.js:26:922259)
      at t (node_modules/onfido-sdk-ui/lib/webpack:/webpack/bootstrap:38:19)
      at node_modules/onfido-sdk-ui/lib/webpack:/external "@babel/runtime-corejs3/helpers/defineProperty":1:26
      at Object.<anonymous> (node_modules/onfido-sdk-ui/lib/webpack:/external "@babel/runtime-corejs3/helpers/defineProperty":1:26)
      at Object.<anonymous> (src/app/components/Kyc/KycDocuments.js:6:1)
      at Object.<anonymous> (src/app/components/Kyc/Kyc.js:28:1)
      at Object.<anonymous> (src/app/components/Kyc/index.js:1:1)
      at Object.<anonymous> (src/app/containers/Dashboard/Dashboard.js:25:1)
      at Object.<anonymous> (src/app/containers/Dashboard/index.js:1:1)
      at Object.<anonymous> (src/app/components/Kyc/Kyc.test.js:9:1)

**Comment by gstrobl** [comment]
I'm not sure whats exactly the problem, but I faced a similar issue. If you trying the test or render the SDK on server-side you got this error, because you need to mock some variables or disable SSR for this component.

**Comment by stefaniacardenas** [comment]
Exactly, this issue usually happens with server-side rendering, so if you are doing that or using a framework that does SSR (eg Next.js) you need to import the SDK asynchronously.

**Comment by Jiuyun-Wang** [comment]
fix it by:

`    useEffect(() => {
            Onfido = await import('onfido-sdk-ui'); //import { init } from "onfido-sdk-ui"; causes test case failed workaround
    }, []);
`
